## Практическое задание к уроку 5

In [37]:
import numpy as np

In [21]:
np.set_printoptions(precision=2, suppress=True)

In [22]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


### Задание 1

##### Создадим переменные U, s, W, представляющие матрицу U, массив сингулярных чисел и транспонированную матрицу V соответственно

In [23]:
U, s, W = np.linalg.svd(A)

##### Получим матрицу V путём транспонирования матрицы W

In [24]:
V = W.T

##### Приведём набор диагональных элементов массива сингулярных чисел к виду диагональной матрицы

In [26]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


##### Выведем матрицу U и докажем её ортогональность

In [27]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [28]:
np.dot(U.T, U)

array([[ 1., -0.,  0.,  0.,  0.],
       [-0.,  1., -0., -0., -0.],
       [ 0., -0.,  1.,  0., -0.],
       [ 0., -0.,  0.,  1., -0.],
       [ 0., -0., -0., -0.,  1.]])

##### Выведем матрицу V и докажем её ортогональность

In [29]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [30]:
np.dot(V.T, V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Выполним проверку, получив исходную матрицу A из матриц U, V и преобразованного массива сингулярных чисел

In [32]:
np.dot(np.dot(U, D), V.T)

array([[ 1.,  2., -0.],
       [-0.,  0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [ 0.,  1.,  0.]])

### Задание 2

##### Вычислим евклидову норму матрицы A

In [42]:
np.linalg.norm(A, ord=2)

8.824868854820442

##### Вычислим норму Фробениуса для матрицы A

In [43]:
np.linalg.norm(A, ord='fro')

11.045361017187261